apiVersion: batch/v1
kind: Job
metadata:
  name: swarm-agent-job
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: agent
        image: swarm-agent:v1
        imagePullPolicy: Never
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: HF_TOKEN
        - name: SENDER_EMAIL
          valueFrom:
            secretKeyRef:
              name: email-secret
              key: SENDER_EMAIL
        - name: SENDER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: email-secret
              key: SENDER_PASSWORD
        - name: RECEIVER_EMAIL
          valueFrom:
            secretKeyRef:
              name: email-secret
              key: RECEIVER_EMAIL
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-secret
              key: TELEGRAM_TOKEN
        - name: TELEGRAM_CHAT_ID
          valueFrom:
            secretKeyRef:
              name: telegram-secret
              key: TELEGRAM_CHAT_ID
      restartPolicy: Never