apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-finance-swarm
spec:
  schedule: "3 21 * * *"
  timeZone: "Europe/Paris"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: agent
            image: swarm-agent:v1
            imagePullPolicy: Never
            env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: HF_TOKEN
            - name: SENDER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: SENDER_EMAIL
            - name: SENDER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: SENDER_PASSWORD
            - name: RECEIVER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: RECEIVER_EMAIL
          restartPolicy: Never